
export var mazmorraDummy= {
    "general": [
        {
            "id": 1,
            "evento_start_id": 0,
            "loot_finish_id": 0,
            "nombre": "Cloaca",
            "descripcion": "Mazmorra Snack 2.0",
            "imagen_id": 0,
            "evento_finish_id": 0,
            "nivel": 9
        }
    ],
    "salas": [
        {
            "id": 1,
            "mazmorra_id": 1,
            "num_sala": 1,
            "evento_final_id": 0,
            "descripcion": "Sala entrada, huele mal pero est\u00e1 tranquila",
            "nombre": "Hall",
            "num_enemigos": 0,
            "evento_inicial_id": 0,
            "num_eventos": 0
        },
        {
            "id": 2,
            "mazmorra_id": 1,
            "num_sala": 2,
            "evento_final_id": 0,
            "descripcion": "La gran sala centra, r\u00edos de heces y bestias ponzo\u00f1osas",
            "nombre": "Cloaca distribuci\u00f3n",
            "num_enemigos": 4,
            "evento_inicial_id": 0,
            "num_eventos": 0
        },
        {
            "id": 3,
            "mazmorra_id": 1,
            "num_sala": 3,
            "evento_final_id": 0,
            "descripcion": "Sala con grandes jerogl\u00edficos, ser\u00e1n importantes?",
            "nombre": "Sala Adivinanza",
            "num_enemigos": 3,
            "evento_inicial_id": 1,
            "num_eventos": 1
        },
        {
            "id": 4,
            "mazmorra_id": 1,
            "num_sala": 4,
            "evento_final_id": 0,
            "descripcion": "It's a TRAP!!",
            "nombre": "Sala Trampa",
            "num_enemigos": 6,
            "evento_inicial_id": 2,
            "num_eventos": 1
        },
        {
            "id": 5,
            "mazmorra_id": 1,
            "num_sala": 5,
            "evento_final_id": 0,
            "descripcion": "Tesoros! Oh no! Montruos!",
            "nombre": "Sala Llave",
            "num_enemigos": 5,
            "evento_inicial_id": 0,
            "num_eventos": 0
        },
        {
            "id": 6,
            "mazmorra_id": 1,
            "num_sala": 6,
            "evento_final_id": 0,
            "descripcion": "Huele a Muerte\u2026",
            "nombre": "Gran Cloaca Ponzo\u00f1osa",
            "num_enemigos": 3,
            "evento_inicial_id": 0,
            "num_eventos": 0
        }
    ],
    "_id": {
        "$oid": "5e55a5ffe0c75357dc429103"
    },
    "enemigos": [
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 2,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 1,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 2,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 2,
            "enemigo_id": 4,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 2,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 3,
            "enemigo_id": 4,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 2,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 4,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 3,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 5,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 3,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 6,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 3,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 7,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 8,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 9,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 10,
            "enemigo_id": 6,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 11,
            "enemigo_id": 6,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 12,
            "enemigo_id": 6,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 4,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 13,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 14,
            "enemigo_id": 4,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 15,
            "enemigo_id": 4,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 16,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 17,
            "enemigo_id": 6,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 18,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 5,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 19,
            "enemigo_id": 5,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 6,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 20,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 6,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 21,
            "enemigo_id": 7,
            "buffo_perma_id": 0,
            "nombre": 0,
            "evento_muerte_id": 0,
            "loot_id": 0
        },
        {
            "loot_prob": 0,
            "imagen_id": 0,
            "sala": 6,
            "evento_intervalo_tiempo": 0,
            "mazmorra_id": 1,
            "evento_intervalo_id": 0,
            "evento_spawn_id": 0,
            "nivel": 9,
            "id": 22,
            "enemigo_id": 8,
            "buffo_perma_id": 0,
            "nombre": "Crocodrile",
            "evento_muerte_id": 0,
            "loot_id": 0
        }
    ],
    "dialogos": [
        {
            "texto3": "-",
            "imagen_id": "narrador",
            "texto1": "Narrador",
            "texto2": "Eh! T\u00fa! Novato.",
            "minimo_tiempo": 0,
            "tipo": "-",
            "texto_elegir": "-",
            "id": 1,
            "eleccion_evento_id": "-",
            "next_evento_id": 0,
            "evento_timeout_id": 0,
            "timeout": 0,
            "redirect_dialogo_id": 2
        },
        {
            "texto3": "-",
            "imagen_id": "narrador",
            "texto1": "Lombuitres",
            "texto2": "\u00bfQui\u00e9n, yo?",
            "minimo_tiempo": 0,
            "tipo": "-",
            "texto_elegir": "-",
            "id": 2,
            "eleccion_evento_id": "-",
            "next_evento_id": 0,
            "evento_timeout_id": 0,
            "timeout": 0,
            "redirect_dialogo_id": 3
        },
        {
            "texto3": "-",
            "imagen_id": "narrador",
            "texto1": "Narrador",
            "texto2": "Si t\u00fa, Bienvenido a Delirium.",
            "minimo_tiempo": 0,
            "tipo": "-",
            "id": 3,
            "eleccion_evento_id": "-",
            "next_evento_id": 0,
            "evento_timeout_id": 0,
            "timeout": 0,
            "redirect_dialogo_id": 0
        }
    ],
    "eventos": [
        {
            "loot_prob": 0,
            "cinematica_id": 0,
            "evento_watcher_id": 0,
            "objetivo_loot": 0,
            "rng_fallo_evento_id": 0,
            "tipo": "Evento",
            "dialogo_id": 1,
            "id": 1,
            "mazmorra_id": 1,
            "buff": 0,
            "spawn_enemigo_id": 0,
            "loot_id": 0,
            "objetivo_dialogo": 0,
            "rng": 0,
            "intervalo_trigger_watcher": 0,
            "sala": 3,
            "if_condicion_variable": 0,
            "if_falso_evento_id": 0,
            "sonido_id": 0,
            "insta_buff": 0,
            "evento_next_id": 0,
            "elimina_variable": 0,
            "codigo": 0,
            "objetivo_buff": "ALL",
            "variable_trigger_watcher": 0,
            "set_evento_watcher": 0,
            "expire_watcher_tiempo": 0,
            "anade_variable": 0,
            "remove_evento_watcher": 0
        },
        {
            "loot_prob": 0,
            "cinematica_id": 0,
            "evento_watcher_id": 0,
            "objetivo_loot": 0,
            "rng_fallo_evento_id": 0,
            "tipo": "Evento",
            "dialogo_id": 0,
            "id": 2,
            "mazmorra_id": 1,
            "buff": 0,
            "spawn_enemigo_id": 0,
            "loot_id": 0,
            "objetivo_dialogo": 0,
            "rng": 0,
            "intervalo_trigger_watcher": 0,
            "sala": 4,
            "if_condicion_variable": 0,
            "if_falso_evento_id": 0,
            "sonido_id": 0,
            "insta_buff": 0,
            "evento_next_id": 0,
            "elimina_variable": 0,
            "codigo": 0,
            "objetivo_buff": "ALL",
            "variable_trigger_watcher": 0,
            "set_evento_watcher": 0,
            "expire_watcher_tiempo": 0,
            "anade_variable": 0,
            "remove_evento_watcher": 0
        }
    ],
    "nombreId": "MazmorraSnack",
    "__v": 0
}